### ISSUE TITLE
[Bug]: browser tab freeze when clicked outside of combox inside dialog

### ISSUE THREAD

**Issue by pigeongit** [unovue/reka-ui#1743]
### Environment

```bash
Developement/Production OS: Fedora Linux 40
Node version: v22.5.1
Package manager: npm@10.8.2
Reka UI version: 2.1.0
Vue version: 3.5.13
CSS framework: tailwindcss@3.4.1
Client OS: Fedora Linux 40
Browser: Google Chrome 134.0.6998.35
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/872wq5

### Steps to reproduce

1. click on the open dialog button
2. click on the open combobox button
3. click on the comboboox title named `test`

### Describe the bug

when clicked on the combo box title named `test` the tab will freeze  in a loop dissmissableLayer.focusout event is being called in an infinite loop.

### Expected behavior

combobox should just close.

### Context & Screenshots (if applicable)

```<script setup lang="ts">

import {
  ComboboxAnchor,
  ComboboxContent,
  ComboboxItem,
  ComboboxPortal,
  ComboboxRoot,
  ComboboxTrigger,
  ComboboxViewport,
  ComboboxInput,
  ComboboxGroup,
  DialogContent,
  DialogPortal,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
} from 'reka-ui';
</script>

<template>
  <DialogRoot>
    <DialogTrigger as-child>
      <button>open dialog</button>
    </DialogTrigger>
    <DialogPortal>
      <DialogContent>
        <DialogTitle>Test</DialogTitle>
        <ComboboxRoot multiple>
          <ComboboxAnchor>
            <ComboboxTrigger>
              open combobox
            </ComboboxTrigger>
          </ComboboxAnchor>
          <ComboboxPortal>
            <ComboboxInput/>
            <ComboboxContent
              class="data-[state=closed]:animate-out" // this line is required to reproduce the bug
            >
              <ComboboxViewport>
                <ComboboxGroup class=""> // this line is required to reproduce the bug
                  <ComboboxItem value="1">Item 1</ComboboxItem> // this line is required to reproduce the bug
                </ComboboxGroup>
              </ComboboxViewport>
            </ComboboxContent>
          </ComboboxPortal>
        </ComboboxRoot>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>```

tailwindcss is required for the bug to appear.

**Comment by ANDRU19** [comment]
I can confirm it. There is some recursion under the Dialog. A temporary solution is to delete the Portal section from the combobox, but this is not a proper fix!

**Comment by joseju77** [comment]
I found that the issue is related to the handleFocusIn function in the FocusScope.vue file.

I wasn't able to run tests to try and fix it properly, but my temporary workaround was to add a focusin event listener directly on the document that stops propagation, preventing handleFocusIn from being triggered.

```ts
// MyComponent.vue
const stopPropagation = (event: Event) => {
    event.stopImmediatePropagation();
};

onBeforeMount(() => {
    document.addEventListener('focusin', stopPropagation);
});

onUnmounted(() => {
    document.removeEventListener('focusin', stopPropagation);
});
```

**Comment by P-James** [comment]
@joseju77 worked for me, thank you!

**Comment by P-James** [comment]
@joseju77  worked for me. Thanks!

**Comment by s-montigny-desautels** [comment]
Another way that worked for me without disabling focusin in all the app, is to prevent the default behaviour of the default focusin handler of the ComboboxContent. It can be disabled like this:

```vue
	<ComboboxContent @focusOutside.prevent>
		<slot />
	</ComboboxContent>
```

**Comment by aled230596** [comment]
> // MyComponent.vue
> const stopPropagation = (event: Event) => {
>     event.stopImmediatePropagation();
> };
> 
> onBeforeMount(() => {
>     document.addEventListener('focusin', stopPropagation);
> });
> 
> onUnmounted(() => {
>     document.removeEventListener('focusin', stopPropagation);
> });


Thanks @joseju77 this workaround worked for me.

**Comment by kerimovok** [comment]
Hello,
Will it be fixed in the package itself?

**Comment by zoir-dev** [comment]
> @focusOutside.prevent

Thank you very much!

**Comment by timmaier** [comment]
> Another way that worked for me without disabling focusin in all the app, is to prevent the default behaviour of the default focusin handler of the ComboboxContent. It can be disabled like this:
> 
> 	<ComboboxContent @focusOutside.prevent>
> 		<slot />
> 	</ComboboxContent>

This solved our issues too wow thankyou!

**Comment by gavgrego** [comment]
Can confirm this issue still exists sadly!  Thank you for the  @focusOutside.prevent fix
